export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_SETUSUARIO = "LOGIN_SETUSUARIO";


export const TEXTOS_LOADING = "TEXTOS_LOADING";
export const TEXTOS_SUCCESS = "TEXTOS_SUCCESS";
export const TEXTOS_ERROR = "TEXTOS_ERROR";
export const TEXTOS_RESET = "TEXTOS_RESET";

export const CHANGE_MODE = "CHANGE_MODE";

export const MODAL_HIDE = "MODAL_HIDE"; 
export const MODAL_SHOW = "MODAL_SHOW"; 

export const TOASTER_HIDE = "TOASTER_HIDE";
export const TOASTER_SHOW = "TOASTER_SHOW";

export const TOKEN_VALIDATION = "TOKEN_VALIDATION"; 
export const TOKEN_VALIDATION_SUCCESS = "TOKEN_VALIDATION_SUCCESS"; 
export const TOKEN_VALIDATION_FAIL = "TOKEN_VALIDATION_FAIL"; 