export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_SETUSUARIO = "LOGIN_SETUSUARIO";

export const REGISTRO_SUCCESS = "REGISTRO_SUCCESS";
export const REGISTRO_LOADING = "REGISTRO_LOADING";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const REGISTRO_RESET = "REGISTRO_RESET";
export const REGISTRO_CAMPOS = "REGISTRO_CAMPOS";
export const REGISTRO_CAMPO_MATRICULA = "REGISTRO_CAMPO_MATRICULA";

export const TOKEN_VALIDATION = "TOKEN_VALIDATION";
export const TOKEN_VALIDATION_SUCCESS = "TOKEN_VALIDATION_SUCCESS";
export const TOKEN_VALIDATION_FAIL = "TOKEN_VALIDATION_FAIL";

export const SET_LIST_ERROR = "SET_LIST_ERROR";
export const LIST_ERROR_RESET = "LIST_ERROR_RESET";

export const LISTAJUEGOS_ERROR = "LISTAJUEGOS_ERROR";
export const LISTAJUEGOS_LOADING = "LISTAJUEGOS_LOADING";
export const LISTAJUEGOS_SUCCESS = "LISTAJUEGOS_SUCCESS";
export const LISTAJUEGOS_RESET = "LISTAJUEGOS_RESET";

export const COLORES_ERROR = "COLORES_ERROR";
export const COLORES_LOADING = "COLORES_LOADING";
export const COLORES_SUCCESS = "COLORES_SUCCESS";
export const COLORES_RESET = "COLORES_RESET";

export const MODAL_SHOW = "MODAL_SHOW";
export const MODAL_HIDE = "MODAL_HIDE";

export const MODAL_AVATAR_SHOW = "MODAL_AVATAR_SHOW";
export const MODAL_AVATAR_HIDE = "MODAL_AVATAR_HIDE";

export const ORDENNUMEROS_ERROR = "ORDENNUMEROS_ERROR";
export const ORDENNUMEROS_LOADING = "ORDENNUMEROS_LOADING";
export const ORDENNUMEROS_SUCCESS = "ORDENNUMEROS_SUCCESS";
export const ORDENNUMEROS_RESET = "ORDENNUMEROS_RESET";
export const VERIFICARNUMEROS_ERROR = "VERIFICARNUMEROS_ERROR";
export const VERIFICARNUMEROS_LOADING = "VERIFICARNUMEROS_LOADING";
export const VERIFICARNUMEROS_SUCCESS = "VERIFICARNUMEROS_SUCCESS";

export const FINALIZA_JUEGO_ERROR = "FINALIZA_JUEGO_ERROR";
export const FINALIZA_JUEGO_LOADING = "FINALIZA_JUEGO_LOADING";
export const FINALIZA_JUEGO_SUCCESS = "FINALIZA_JUEGO_SUCCESS";
export const FINALIZA_JUEGO_RESET = "FINALIZA_JUEGO_RESET";

export const MISPACIENTES_ERROR = "MISPACIENTES_ERROR";
export const MISPACIENTES_LOADING = "MISPACIENTES_LOADING";
export const MISPACIENTES_SUCCESS = "MISPACIENTES_SUCCESS";
export const MISPACIENTES_RESET = "MISPACIENTES_RESET";
export const HABILITAR_PACIENTE_SUCCESS = "HABILITAR_PACIENTE_SUCCESS";

export const PROFESIONALES_ERROR = "PROFESIONALES_ERROR";
export const PROFESIONALES_LOADING = "PROFESIONALES_LOADING";
export const PROFESIONALES_SUCCESS = "PROFESIONALES_SUCCESS";
export const PROFESIONALES_RESET = "PROFESIONALES_RESET";
export const HABILITAR_PROFESIONAL_LOADING = "HABILITAR_PROFESIONAL_LOADING";
export const HABILITAR_PROFESIONAL_ERROR = "HABILITAR_PROFESIONAL_ERROR";
export const HABILITAR_PROFESIONAL_SUCCESS = "HABILITAR_PROFESIONAL_SUCCESS";