export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_SETUSUARIO = "LOGIN_SETUSUARIO";

export const REGISTRO_SUCCESS = "REGISTRO_SUCCESS";
export const REGISTRO_LOADING = "REGISTRO_LOADING";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const REGISTRO_RESET = "REGISTRO_RESET";

export const TOKEN_VALIDATION = "TOKEN_VALIDATION";
export const TOKEN_VALIDATION_SUCCESS = "TOKEN_VALIDATION_SUCCESS";
export const TOKEN_VALIDATION_FAIL = "TOKEN_VALIDATION_FAIL";


export const SET_LIST_ERROR = "SET_LIST_ERROR";
export const LIST_ERROR_RESET = "LIST_ERROR_RESET";



